export const ADD_COMPANY_TO_PORTFOLIO = "ADD_COMPANY_TO_PORTFOLIO";
export const CHANGE_SEARCHED_COMPANIES = "CHANGE_SEARCHED_COMPANIES";
export const REMOVE_COMPANY_FROM_PORTFOLIO = "REMOVE_COMPANY_FROM_PORTFOLIO";
